### ISSUE TITLE
Tracking issue of CI failures until next sync

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control_ci#202]
testing
http://packages.ros.org/ros2-testing/ubuntu/dists/noble/main/binary-amd64/Packages
http://packages.ros.org/ros2-testing/ubuntu/dists/jammy/main/binary-amd64/Packages
main
http://packages.ros.org/ros2/ubuntu/dists/noble/main/binary-amd64/Packages
http://packages.ros.org/ros2/ubuntu/dists/jammy/main/binary-amd64/Packages

## ros2_controllers

Rolling 4.21
- [x] https://github.com/ros-controls/ros2_control_demos/pull/710
- [x] https://github.com/ros-controls/ros2_control_demos/issues/739

Jazzy 4.21
- [x] https://github.com/ros-controls/ros2_control_demos/pull/710

## ros2_control

Rolling 4.27

- [x] https://github.com/ros-controls/ros2_controllers/issues/1541
- [x] https://github.com/ros-controls/ros2_controllers/issues/1542
- [x] https://github.com/ros-controls/ros2_control_demos/pull/710

Jazzy 4.27

- [x] https://github.com/ros-controls/ros2_controllers/issues/1543
- [x] https://github.com/ros-controls/ros2_controllers/issues/1544
- [x] https://github.com/ros-controls/ros2_control_demos/pull/710

Rolling 4.25

- [x] https://github.com/ros-controls/ros2_control_demos/pull/548

Jazzy 4.25

- [x] https://github.com/ros-controls/ros2_control_demos/pull/548

Rolling 4.23

- [x] https://github.com/ros-controls/ros2_control_demos/pull/673

Rolling 4.22

- [x] https://github.com/ros-controls/ros2_control_demos/pull/653

Rolling 4.21

Jazzy 4.23

- [x] https://github.com/ros-controls/ros2_control_demos/pull/673

Jazzy 4.22

- [x] https://github.com/ros-controls/ros2_control_demos/pull/653
- [x] https://github.com/ros-controls/ros2_control_demos/issues/684

Jazzy 4.21

- [x] https://github.com/ros-controls/ros2_control_demos/issues/670

Humble 2.46

- [x] https://github.com/ros-controls/ros2_control_demos/issues/671

## realtime_tools

 Rolling 3.1.0

- [x] https://github.com/ros-controls/realtime_tools/issues/241

 Rolling 3.0.0

- [x] https://github.com/ros-controls/control_toolbox/issues/250
- [x] https://github.com/ros-controls/ros2_control/issues/1853
- [x] https://github.com/ros-controls/ros2_controllers/issues/1308
- [x] https://github.com/ros-controls/ros2_control_demos/issues/672
- [x] https://github.com/ros-controls/realtime_tools/issues/203

Jazzy 3.1.0

- [x] https://github.com/ros-controls/realtime_tools/issues/241

Jazzy 3.0.0

- [x] https://github.com/ros-controls/control_toolbox/issues/248
- [x] https://github.com/ros-controls/ros2_control/issues/1913
- [x] https://github.com/ros-controls/ros2_controllers/issues/1408
- [x] https://github.com/ros-controls/ros2_control_ci/issues/186
- [x] https://github.com/ros-controls/realtime_tools/issues/203

Humble 2.10

- [x] https://github.com/ros-controls/control_toolbox/issues/249
- [x] https://github.com/ros-controls/ros2_control/issues/1859

# control_toolbox

Rolling 4.0.0

- [x] https://github.com/ros-controls/gazebo_ros2_control/pull/395
- [x] https://github.com/ros-controls/ros2_controllers/pull/1437

Jazzy 4.0.0

- [x] https://github.com/ros-controls/gazebo_ros2_control/pull/395
- [x] https://github.com/ros-controls/ros2_controllers/pull/1437

Jazzy 3.5.0

- [x] https://github.com/ros-controls/control_toolbox/issues/259

# control_msgs
Rolling 6.0.0

- [x] https://github.com/ros-controls/control_toolbox/issues/305
- [x] https://github.com/ros-controls/control_toolbox/issues/304

## generate_parameter_library
Rolling 0.4.0

- [x] https://github.com/ros-controls/control_toolbox/issues/269
- [x] https://github.com/ros-controls/ros2_control/issues/2003
- [x] https://github.com/ros-controls/ros2_control_ci/issues/230
- [x] https://github.com/ros-controls/ros2_controllers/issues/1494

Jazzy 0.4.0

- [x] https://github.com/ros-controls/control_toolbox/issues/268
- [x] https://github.com/ros-controls/ros2_control/issues/2004
- [x] https://github.com/ros-controls/ros2_controllers/issues/1495
- [x] https://github.com/ros-controls/ros2_control_ci/issues/229
- [x] https://github.com/ros-controls/control_toolbox/issues/275

Humble 0.4.0

- [x] https://github.com/ros-controls/control_toolbox/issues/267
- [x] https://github.com/ros-controls/ros2_control_ci/issues/231
- [x] https://github.com/ros-controls/ros2_controllers/issues/1497
- [x] https://github.com/ros-controls/control_toolbox/issues/274
- [x] https://github.com/ros-controls/ros2_controllers/issues/1500

**Comment by christophfroehlich** [comment]
Moved to https://github.com/orgs/ros-controls/projects/9
